spring:
  profiles:
    active: master

my:
  name: monkey
  age: 500

your:
  resource:
    aaa,bbb,ccc,ddd
  map:
    k1: v1,
    k2: v2,
    k3: v3

#车联体密钥
clt:
  privateKey: MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAMIRxxLC5NZjovm8rd8JY5K8EIU/SQgkd+rg84HXEf78gKA8pa9fza7OWtuYRZz9car8TDUCgJNSPIZHuf5w1JIDoOH6qNZpbMJ2nM03SvyAY3Wt8D4+4wRfA3/CAHtpL5E2Z/KGSLhhPcnKwSFGqbrcuqRTRMWcPry8459gp5G9AgMBAAECgYBOrfpxpsY0DQ0kBtTPGfVephRkkTXAsVhUx4Kx30oSgLh9PllF8qdm+Y5ofSGr9izBT6xtyWfrUmnrXuUPPRtQqmaTayA+ihDcXPba+TlRl4H7VYpGJQVbWgCQ2cD7k+eG7LEZpea/JBb/34pJWdCJbr6uvh6jgY1Jw+g7MlXvWQJBAOpHNIVezTX7wjsfSVTroLtj/3PDDYGZBfFmFGyo7CbdkBaorROzPdJWbyBL6WAaL+FAWrp4GrDbbojDqc6NQfMCQQDUEC8gvICJQX8gRP9OkeU7kcULqbIpnBRwxqYGuP6SjKJy+TF0gdA+Qg7GpeyJBqNJ3chdkeXw8wHiK5F/NRmPAkBFXUfDpUoFDcF4V88SgaFZWkYsNDgvgusrihnKAknJSBh9XPvBtXQ8brMAUPmMJrS+cJtsUls0ugOEIsqICXLZAkB4wl6T/cQUZT/HWIMqctpe+buD0LasCz14myagXWhae8tmPZF0DxhO278eUA5KWYVS4wDeh96xPzCrYrQQBGTxAkEA3dIZc6W/RxIr/06BT1mAkoJBA83TGYHv0LWOdf5WEi7YVKI/7qNEXeFAUhXzgtD/UIvAdNNRcmeSUXkyuAqw8w==


#正式
dlb:
  accessKey: c892b2e78a9947638e075f51d0fff4d1f3aad64b
  secretKey: e7e59a713ce54b81b1131322e3bb3173513270c9
  customerNum: 10001115626588386620056
  shopNum: 10001215626593159947259
  callbackUrl: http://adsgodlove.vicp.cc:44674/payservice/duolabaoNotify

#测试
dlb2:
  accessKey: 3b80943398cb4194a48a89abf81deb4b1633a815
  secretKey: 4fcfda16f7a14905bdda6daa9a6ea3eb5444533c
  customerNum: 10001115525569710821582
  shopNum: 10001215525571169599125
  callbackUrl: http://adsgodlove.vicp.cc:44674/payservice/duolabaoNotify


account:
  type:
    - A004-001-001
    - A004-001-002
    - A004-001-003
    - A004-001-004

recharge:
  status:
    [success,fail,paying]